import type { Part } from '../types.js';

export const allenBradleyParts: Omit<Part, 'id' | 'createdAt' | 'modifiedAt'>[] = [
  {
    type: 'part',
    manufacturer: 'Allen-Bradley',
    partNumber: '1769-L33ER',
    description: 'CompactLogix 5370 L3 Controller',
    category: 'plc-cpu',
    voltage: '24VDC',
    certifications: ['UL', 'CE', 'CSA'],
    symbolCategory: 'plc-cpu',
    attributes: { series: 'CompactLogix', memory: '2MB', ethernetPorts: 2 },
  },
  {
    type: 'part',
    manufacturer: 'Allen-Bradley',
    partNumber: '1769-IQ16',
    description: 'CompactLogix 16-Point Digital Input Module',
    category: 'plc-di-16',
    voltage: '24VDC',
    current: '5.5mA/point',
    certifications: ['UL', 'CE', 'CSA'],
    symbolCategory: 'plc-di-16',
    attributes: { series: 'CompactLogix', channels: 16, inputType: 'sink/source' },
  },
  {
    type: 'part',
    manufacturer: 'Allen-Bradley',
    partNumber: '1769-OB16',
    description: 'CompactLogix 16-Point Digital Output Module',
    category: 'plc-do-16',
    voltage: '24VDC',
    current: '0.5A/point',
    certifications: ['UL', 'CE', 'CSA'],
    symbolCategory: 'plc-do-16',
    attributes: { series: 'CompactLogix', channels: 16, outputType: 'source' },
  },
  {
    type: 'part',
    manufacturer: 'Allen-Bradley',
    partNumber: '1769-IF8',
    description: 'CompactLogix 8-Channel Analog Input Module',
    category: 'plc-ai-8',
    voltage: '24VDC',
    certifications: ['UL', 'CE', 'CSA'],
    symbolCategory: 'plc-ai-8',
    attributes: { series: 'CompactLogix', channels: 8, resolution: '16-bit', inputRange: '0-10V / 4-20mA' },
  },
  {
    type: 'part',
    manufacturer: 'Allen-Bradley',
    partNumber: '1769-OF4',
    description: 'CompactLogix 4-Channel Analog Output Module',
    category: 'plc-ao-4',
    voltage: '24VDC',
    certifications: ['UL', 'CE', 'CSA'],
    symbolCategory: 'plc-ao-4',
    attributes: { series: 'CompactLogix', channels: 4, resolution: '16-bit', outputRange: '0-10V / 4-20mA' },
  },
  {
    type: 'part',
    manufacturer: 'Allen-Bradley',
    partNumber: '1769-PA4',
    description: 'CompactLogix Power Supply Module',
    category: 'plc-ps',
    voltage: '120/240VAC',
    current: '4A @ 5VDC',
    certifications: ['UL', 'CE', 'CSA'],
    symbolCategory: 'plc-ps',
    attributes: { series: 'CompactLogix', inputVoltage: '85-265VAC' },
  },
];
