import type { Part } from '../types.js';

export const allenBradleyParts: Omit<Part, 'id' | 'createdAt' | 'modifiedAt'>[] = [
  {
    type: 'part',
    manufacturer: 'Allen-Bradley',
    partNumber: '1769-L33ER',
    description: 'CompactLogix 5370 L3 Controller',
    category: 'plc-cpu',
    voltage: '24VDC',
    certifications: ['UL', 'CE', 'CSA'],
    symbolCategory: 'plc-cpu',
    attributes: { series: 'CompactLogix', memory: '2MB', ethernetPorts: 2 },
  },
  {
    type: 'part',
    manufacturer: 'Allen-Bradley',
    partNumber: '1769-IQ16',
    description: 'CompactLogix 16-Point Digital Input Module',
    category: 'plc-di-16',
    voltage: '24VDC',
    current: '5.5mA/point',
    certifications: ['UL', 'CE', 'CSA'],
    symbolCategory: 'plc-di-16',
    attributes: { series: 'CompactLogix', channels: 16, inputType: 'sink/source' },
  },
  {
    type: 'part',
    manufacturer: 'Allen-Bradley',
    partNumber: '1769-OB16',
    description: 'CompactLogix 16-Point Digital Output Module',
    category: 'plc-do-16',
    voltage: '24VDC',
    current: '0.5A/point',
    certifications: ['UL', 'CE', 'CSA'],
    symbolCategory: 'plc-do-16',
    attributes: { series: 'CompactLogix', channels: 16, outputType: 'source' },
  },
  {
    type: 'part',
    manufacturer: 'Allen-Bradley',
    partNumber: '1769-IF8',
    description: 'CompactLogix 8-Channel Analog Input Module',
    category: 'plc-ai-8',
    voltage: '24VDC',
    certifications: ['UL', 'CE', 'CSA'],
    symbolCategory: 'plc-ai-8',
    attributes: { series: 'CompactLogix', channels: 8, resolution: '16-bit', inputRange: '0-10V / 4-20mA' },
  },
  {
    type: 'part',
    manufacturer: 'Allen-Bradley',
    partNumber: '1769-OF4',
    description: 'CompactLogix 4-Channel Analog Output Module',
    category: 'plc-ao-4',
    voltage: '24VDC',
    certifications: ['UL', 'CE', 'CSA'],
    symbolCategory: 'plc-ao-4',
    attributes: { series: 'CompactLogix', channels: 4, resolution: '16-bit', outputRange: '0-10V / 4-20mA' },
  },
  {
    type: 'part',
    manufacturer: 'Allen-Bradley',
    partNumber: '1769-PA4',
    description: 'CompactLogix Power Supply Module',
    category: 'plc-ps',
    voltage: '120/240VAC',
    current: '4A @ 5VDC',
    certifications: ['UL', 'CE', 'CSA'],
    symbolCategory: 'plc-ps',
    attributes: { series: 'CompactLogix', inputVoltage: '85-265VAC' },
  },

  // --- Micro800 Series (multi-symbol parts) ---
  {
    type: 'part',
    manufacturer: 'Allen-Bradley',
    partNumber: '2080-LC50-24QBB',
    description: 'Micro850 PLC - 14 DI / 10 DO (24VDC)',
    category: 'plc',
    voltage: '24VDC',
    certifications: ['UL', 'CE', 'CSA'],
    symbolCategory: 'ab-2080-lc50-24-input',  // primary symbol
    requiredSymbols: [
      { symbolId: 'ab-2080-lc50-24-input', role: 'DI Module (14 inputs)', isPrimary: true },
      { symbolId: 'ab-2080-lc50-24-output', role: 'DO Module (10 outputs)' },
    ],
    attributes: { series: 'Micro800', model: 'Micro850', diCount: 14, doCount: 10 },
  },
  {
    type: 'part',
    manufacturer: 'Allen-Bradley',
    partNumber: '2080-LC50-24QVB',
    description: 'Micro850 PLC - 14 DI / 10 DO (24VDC, high-speed)',
    category: 'plc',
    voltage: '24VDC',
    certifications: ['UL', 'CE', 'CSA'],
    symbolCategory: 'ab-2080-lc50-24-input',
    requiredSymbols: [
      { symbolId: 'ab-2080-lc50-24-input', role: 'DI Module (14 inputs)', isPrimary: true },
      { symbolId: 'ab-2080-lc50-24-output', role: 'DO Module (10 outputs)' },
    ],
    attributes: { series: 'Micro800', model: 'Micro850', diCount: 14, doCount: 10 },
  },
  // ---- 700-H Series Ice Cube / Slim Relays ----
  {
    type: 'part',
    manufacturer: 'Allen-Bradley',
    partNumber: '700-HK36Z24-3-4',
    description: 'Relay, Slim Line, 5-Blade, 1PDT, 16A, 24VDC',
    category: 'relay',
    voltage: '24VDC',
    current: '16A',
    certifications: ['UL', 'CE', 'CSA'],
    symbolCategory: 'ansi-coil',
    pinMappings: {
      'ansi-coil': { '1': 'A1', '2': 'A2' },
      'ansi-normally-open-contact': { '1': '11', '2': '14' },
      'ansi-normally-closed-contact': { '1': '11', '2': '12' },
    },
    attributes: { series: '700-HK', poles: 1, configuration: '1PDT', socket: '700-HN121' },
  },
  {
    type: 'part',
    manufacturer: 'Allen-Bradley',
    partNumber: '700-HA32Z24',
    description: 'Relay, Ice Cube, 8-Pin, 2PDT, 10A, 24VDC',
    category: 'relay',
    voltage: '24VDC',
    current: '10A',
    certifications: ['UL', 'CE', 'CSA'],
    symbolCategory: 'ansi-coil',
    pinMappings: {
      'ansi-coil': { '1': 'A1', '2': 'A2' },
      // 8-pin 2PDT: pole 1 = 11/14 (NO) or 11/12 (NC), pole 2 = 21/24 (NO) or 21/22 (NC)
      'ansi-normally-open-contact': { '1': '11', '2': '14' },
      'ansi-normally-closed-contact': { '1': '11', '2': '12' },
    },
    attributes: { series: '700-HA', poles: 2, configuration: '2PDT', socket: '700-HN100' },
  },
  {
    type: 'part',
    manufacturer: 'Allen-Bradley',
    partNumber: '700-HN121',
    description: 'Socket, 5-Blade, Miniature, Includes Retainer Clip (for 700-HK)',
    category: 'relay-socket',
    certifications: ['UL', 'CE', 'CSA'],
    attributes: { compatibleRelay: '700-HK', mounting: 'Panel/DIN Rail' },
  },
  {
    type: 'part',
    manufacturer: 'Allen-Bradley',
    partNumber: '700-HN100',
    description: 'Socket, 8-Pin, Tube Base, Screw Terminal, Panel/DIN Rail Mount',
    category: 'relay-socket',
    certifications: ['UL', 'CE', 'CSA'],
    attributes: { compatibleRelay: '700-HA', mounting: 'Panel/DIN Rail' },
  },
  // ---- 1606-XLS Power Supplies ----
  {
    type: 'part',
    manufacturer: 'Allen-Bradley',
    partNumber: '1606-XLS240E',
    description: 'Power Supply, Performance, 240W, 24-28VDC, 1-Phase',
    category: 'power-supply',
    voltage: '24-28VDC',
    powerRating: '240W',
    certifications: ['UL', 'CE', 'CSA'],
    symbolCategory: 'iec-power-supply-ac-dc',
    layoutSymbolId: 'layout-1606-xls240e',
    attributes: { series: '1606-XLS', input: '120-240VAC' },
  },
  {
    type: 'part',
    manufacturer: 'Allen-Bradley',
    partNumber: '1606-XLS240-UPS',
    description: 'Charging Module, 240W, 22.5-30VDC, with UPS',
    category: 'ups',
    voltage: '22.5-30VDC',
    powerRating: '240W',
    certifications: ['UL', 'CE', 'CSA'],
    symbolCategory: 'ups-dc-24v',
    layoutSymbolId: 'layout-1606-xls240-ups',
    attributes: { series: '1606-XLS', batteryBackup: true },
  },
];
