import type { Part } from '../types.js';

export const phoenixContactParts: Omit<Part, 'id' | 'createdAt' | 'modifiedAt'>[] = [
  {
    type: 'part',
    manufacturer: 'Phoenix Contact',
    partNumber: '3044076',
    description: 'UT 2.5 - Feed-through terminal block',
    category: 'single-terminal',
    voltage: '800V',
    current: '24A',
    certifications: ['UL', 'CE', 'CSA'],
    symbolCategory: 'single-terminal',
    attributes: { series: 'UT', crossSection: '2.5mm²', color: 'gray' },
  },
  {
    type: 'part',
    manufacturer: 'Phoenix Contact',
    partNumber: '3044102',
    description: 'UT 4 - Feed-through terminal block',
    category: 'single-terminal',
    voltage: '800V',
    current: '32A',
    certifications: ['UL', 'CE', 'CSA'],
    symbolCategory: 'single-terminal',
    attributes: { series: 'UT', crossSection: '4mm²', color: 'gray' },
  },
  {
    type: 'part',
    manufacturer: 'Phoenix Contact',
    partNumber: '3044128',
    description: 'UT 6 - Feed-through terminal block',
    category: 'single-terminal',
    voltage: '800V',
    current: '41A',
    certifications: ['UL', 'CE', 'CSA'],
    symbolCategory: 'single-terminal',
    attributes: { series: 'UT', crossSection: '6mm²', color: 'gray' },
  },
  {
    type: 'part',
    manufacturer: 'Phoenix Contact',
    partNumber: '3044209',
    description: 'UTTB 2.5 - Double-level terminal block',
    category: 'dual-terminal',
    voltage: '500V',
    current: '24A',
    certifications: ['UL', 'CE', 'CSA'],
    symbolCategory: 'dual-terminal',
    attributes: { series: 'UTTB', crossSection: '2.5mm²', color: 'gray' },
  },
  {
    type: 'part',
    manufacturer: 'Phoenix Contact',
    partNumber: '3213974',
    description: 'UTTB 2.5-PE - Ground terminal block',
    category: 'ground-terminal',
    voltage: '500V',
    current: '24A',
    certifications: ['UL', 'CE', 'CSA'],
    symbolCategory: 'ground-terminal',
    attributes: { series: 'UTTB', crossSection: '2.5mm²', color: 'green-yellow' },
  },
  {
    type: 'part',
    manufacturer: 'Phoenix Contact',
    partNumber: '3046032',
    description: 'UT 4-HESI - Fuse terminal block',
    category: 'fuse-terminal',
    voltage: '500V',
    current: '6.3A',
    certifications: ['UL', 'CE', 'CSA'],
    symbolCategory: 'fuse-terminal',
    attributes: { series: 'UT', crossSection: '4mm²', fuseType: '5x20mm' },
  },
  {
    type: 'part',
    manufacturer: 'Phoenix Contact',
    partNumber: '3070048',
    description: 'D-UT 2.5/10 - End cover',
    category: 'accessory',
    attributes: { series: 'UT', color: 'gray', itemType: 'end-cover' },
  },
  {
    type: 'part',
    manufacturer: 'Phoenix Contact',
    partNumber: '3030161',
    description: 'FBS 2-5 - Plug-in bridge 2-way',
    category: 'accessory',
    current: '25A',
    attributes: { series: 'FBS', ways: 2, itemType: 'jumper' },
  },
];
