import type { Part } from '../types.js';

export const schneiderElectricParts: Omit<Part, 'id' | 'createdAt' | 'modifiedAt'>[] = [
  {
    type: 'part',
    manufacturer: 'Schneider Electric',
    partNumber: 'LC1D09',
    description: 'TeSys D Contactor - 9A, 3P, 24VDC coil',
    category: 'contactor',
    voltage: '690VAC',
    current: '9A',
    certifications: ['UL', 'CE', 'CSA', 'IEC'],
    symbolCategory: 'contactor',
    attributes: { series: 'TeSys D', poles: 3, coilVoltage: '24VDC', AC3Rating: '4kW' },
  },
  {
    type: 'part',
    manufacturer: 'Schneider Electric',
    partNumber: 'LC1D18',
    description: 'TeSys D Contactor - 18A, 3P, 24VDC coil',
    category: 'contactor',
    voltage: '690VAC',
    current: '18A',
    certifications: ['UL', 'CE', 'CSA', 'IEC'],
    symbolCategory: 'contactor',
    attributes: { series: 'TeSys D', poles: 3, coilVoltage: '24VDC', AC3Rating: '7.5kW' },
  },
  {
    type: 'part',
    manufacturer: 'Schneider Electric',
    partNumber: 'LC1D32',
    description: 'TeSys D Contactor - 32A, 3P, 24VDC coil',
    category: 'contactor',
    voltage: '690VAC',
    current: '32A',
    certifications: ['UL', 'CE', 'CSA', 'IEC'],
    symbolCategory: 'contactor',
    attributes: { series: 'TeSys D', poles: 3, coilVoltage: '24VDC', AC3Rating: '15kW' },
  },
  {
    type: 'part',
    manufacturer: 'Schneider Electric',
    partNumber: 'LRD08',
    description: 'TeSys LRD Overload Relay - 2.5-4A',
    category: 'overload',
    current: '2.5-4A',
    certifications: ['UL', 'CE', 'CSA', 'IEC'],
    symbolCategory: 'overload',
    attributes: { series: 'TeSys LRD', tripClass: '10', resetType: 'manual/auto' },
  },
  {
    type: 'part',
    manufacturer: 'Schneider Electric',
    partNumber: 'LRD14',
    description: 'TeSys LRD Overload Relay - 7-10A',
    category: 'overload',
    current: '7-10A',
    certifications: ['UL', 'CE', 'CSA', 'IEC'],
    symbolCategory: 'overload',
    attributes: { series: 'TeSys LRD', tripClass: '10', resetType: 'manual/auto' },
  },
  {
    type: 'part',
    manufacturer: 'Schneider Electric',
    partNumber: 'GV2ME08',
    description: 'GV2 Motor Circuit Breaker - 2.5-4A',
    category: 'circuit-breaker',
    voltage: '690VAC',
    current: '2.5-4A',
    certifications: ['UL', 'CE', 'CSA', 'IEC'],
    symbolCategory: 'circuit-breaker',
    attributes: { series: 'GV2', breakingCapacity: '100kA', poles: 3 },
  },
  {
    type: 'part',
    manufacturer: 'Schneider Electric',
    partNumber: 'GV2ME14',
    description: 'GV2 Motor Circuit Breaker - 6-10A',
    category: 'circuit-breaker',
    voltage: '690VAC',
    current: '6-10A',
    certifications: ['UL', 'CE', 'CSA', 'IEC'],
    symbolCategory: 'circuit-breaker',
    attributes: { series: 'GV2', breakingCapacity: '100kA', poles: 3 },
  },
  {
    type: 'part',
    manufacturer: 'Schneider Electric',
    partNumber: 'XB4BA21',
    description: 'Harmony XB4 Pushbutton - Green, Flush, NO',
    category: 'button',
    voltage: '600VAC',
    current: '10A',
    certifications: ['UL', 'CE', 'CSA'],
    symbolCategory: 'button',
    attributes: { series: 'Harmony XB4', color: 'green', contactType: 'NO', actuator: 'flush' },
  },
  {
    type: 'part',
    manufacturer: 'Schneider Electric',
    partNumber: 'XB4BA42',
    description: 'Harmony XB4 Pushbutton - Red, Flush, NC',
    category: 'button',
    voltage: '600VAC',
    current: '10A',
    certifications: ['UL', 'CE', 'CSA'],
    symbolCategory: 'button',
    attributes: { series: 'Harmony XB4', color: 'red', contactType: 'NC', actuator: 'flush' },
  },
];
