import type { Part } from '../types.js';

/**
 * Schneider Electric Harmony XB4/XB5 Pushbuttons, Pilot Lights, Selector Switches, E-Stops
 *
 * Common control panel operator interface devices.
 * symbolCategory maps to fusionCad symbol IDs for BOM check matching.
 */
export const schneiderPushbuttonParts: Omit<Part, 'id' | 'createdAt' | 'modifiedAt'>[] = [

  // --- Pushbuttons (NO) ---
  {
    type: 'part',
    manufacturer: 'Schneider Electric',
    partNumber: 'XB4BA31',
    description: 'Harmony XB4 Pushbutton - Green, Flush, 1NO',
    category: 'pushbutton',
    voltage: '600VAC',
    current: '10A',
    certifications: ['UL', 'CE', 'CSA'],
    symbolCategory: 'iec-no-contact',
    datasheetUrl: 'https://www.se.com/us/en/product/XB4BA31/',
    attributes: { series: 'Harmony XB4', color: 'green', contactType: '1NO', actuator: 'flush', mounting: '22mm' },
  },
  {
    type: 'part',
    manufacturer: 'Schneider Electric',
    partNumber: 'XB4BA21',
    description: 'Harmony XB4 Pushbutton - Green, Flush, 1NO',
    category: 'pushbutton',
    voltage: '600VAC',
    current: '10A',
    certifications: ['UL', 'CE', 'CSA'],
    symbolCategory: 'iec-no-contact',
    datasheetUrl: 'https://www.se.com/us/en/product/XB4BA21/',
    attributes: { series: 'Harmony XB4', color: 'green', contactType: '1NO', actuator: 'flush', mounting: '22mm' },
  },

  // --- Pushbuttons (NC) ---
  {
    type: 'part',
    manufacturer: 'Schneider Electric',
    partNumber: 'XB4BA42',
    description: 'Harmony XB4 Pushbutton - Red, Flush, 1NC',
    category: 'pushbutton',
    voltage: '600VAC',
    current: '10A',
    certifications: ['UL', 'CE', 'CSA'],
    symbolCategory: 'iec-nc-contact',
    datasheetUrl: 'https://www.se.com/us/en/product/XB4BA42/',
    attributes: { series: 'Harmony XB4', color: 'red', contactType: '1NC', actuator: 'flush', mounting: '22mm' },
  },

  // --- E-Stop ---
  {
    type: 'part',
    manufacturer: 'Schneider Electric',
    partNumber: 'XB4BS8442',
    description: 'Harmony XB4 E-Stop - Red Mushroom Head, 40mm, 1NC, Turn-to-Release',
    category: 'e-stop',
    voltage: '600VAC',
    current: '10A',
    certifications: ['UL', 'CE', 'CSA', 'ISO 13850'],
    symbolCategory: 'iec-nc-contact',
    datasheetUrl: 'https://www.se.com/us/en/product/XB4BS8442/',
    attributes: { series: 'Harmony XB4', color: 'red', contactType: '1NC', actuator: 'mushroom-head', diameter: '40mm', reset: 'turn-to-release', mounting: '22mm' },
  },
  {
    type: 'part',
    manufacturer: 'Schneider Electric',
    partNumber: 'XB4BT845',
    description: 'Harmony XB4 E-Stop - Red Mushroom Head, 40mm, 2NC, Turn-to-Release',
    category: 'e-stop',
    voltage: '600VAC',
    current: '10A',
    certifications: ['UL', 'CE', 'CSA', 'ISO 13850'],
    symbolCategory: 'iec-nc-contact',
    datasheetUrl: 'https://www.se.com/us/en/product/XB4BT845/',
    attributes: { series: 'Harmony XB4', color: 'red', contactType: '2NC', actuator: 'mushroom-head', diameter: '40mm', reset: 'turn-to-release', mounting: '22mm' },
  },

  // --- Pilot Lights ---
  {
    type: 'part',
    manufacturer: 'Schneider Electric',
    partNumber: 'XB4BVB3',
    description: 'Harmony XB4 Pilot Light - Green, LED, 24VAC/DC',
    category: 'pilot-light',
    voltage: '24VAC/DC',
    certifications: ['UL', 'CE', 'CSA'],
    symbolCategory: 'iec-indicator-light',
    datasheetUrl: 'https://www.se.com/us/en/product/XB4BVB3/',
    attributes: { series: 'Harmony XB4', color: 'green', lampType: 'LED', mounting: '22mm' },
  },
  {
    type: 'part',
    manufacturer: 'Schneider Electric',
    partNumber: 'XB4BVB4',
    description: 'Harmony XB4 Pilot Light - Red, LED, 24VAC/DC',
    category: 'pilot-light',
    voltage: '24VAC/DC',
    certifications: ['UL', 'CE', 'CSA'],
    symbolCategory: 'iec-indicator-light',
    datasheetUrl: 'https://www.se.com/us/en/product/XB4BVB4/',
    attributes: { series: 'Harmony XB4', color: 'red', lampType: 'LED', mounting: '22mm' },
  },
  {
    type: 'part',
    manufacturer: 'Schneider Electric',
    partNumber: 'XB4BVB5',
    description: 'Harmony XB4 Pilot Light - Amber/Orange, LED, 24VAC/DC',
    category: 'pilot-light',
    voltage: '24VAC/DC',
    certifications: ['UL', 'CE', 'CSA'],
    symbolCategory: 'iec-indicator-light',
    datasheetUrl: 'https://www.se.com/us/en/product/XB4BVB5/',
    attributes: { series: 'Harmony XB4', color: 'amber', lampType: 'LED', mounting: '22mm' },
  },
  {
    type: 'part',
    manufacturer: 'Schneider Electric',
    partNumber: 'XB4BVM3',
    description: 'Harmony XB4 Pilot Light - Green, LED, 230VAC',
    category: 'pilot-light',
    voltage: '230VAC',
    certifications: ['UL', 'CE', 'CSA'],
    symbolCategory: 'iec-indicator-light',
    datasheetUrl: 'https://www.se.com/us/en/product/XB4BVM3/',
    attributes: { series: 'Harmony XB4', color: 'green', lampType: 'LED', mounting: '22mm' },
  },
  {
    type: 'part',
    manufacturer: 'Schneider Electric',
    partNumber: 'XB4BVM4',
    description: 'Harmony XB4 Pilot Light - Red, LED, 230VAC',
    category: 'pilot-light',
    voltage: '230VAC',
    certifications: ['UL', 'CE', 'CSA'],
    symbolCategory: 'iec-indicator-light',
    datasheetUrl: 'https://www.se.com/us/en/product/XB4BVM4/',
    attributes: { series: 'Harmony XB4', color: 'red', lampType: 'LED', mounting: '22mm' },
  },

  // --- Selector Switches ---
  {
    type: 'part',
    manufacturer: 'Schneider Electric',
    partNumber: 'XB4BD21',
    description: 'Harmony XB4 Selector Switch - 2-Position, Stay-Put, 1NO',
    category: 'selector-switch',
    voltage: '600VAC',
    current: '10A',
    certifications: ['UL', 'CE', 'CSA'],
    symbolCategory: 'iec-no-contact',
    datasheetUrl: 'https://www.se.com/us/en/product/XB4BD21/',
    attributes: { series: 'Harmony XB4', positions: 2, returnType: 'stay-put', contactType: '1NO', mounting: '22mm' },
  },
  {
    type: 'part',
    manufacturer: 'Schneider Electric',
    partNumber: 'XB4BD33',
    description: 'Harmony XB4 Selector Switch - 3-Position (HOA), Stay-Put, 2NO',
    category: 'selector-switch',
    voltage: '600VAC',
    current: '10A',
    certifications: ['UL', 'CE', 'CSA'],
    symbolCategory: 'iec-no-contact',
    datasheetUrl: 'https://www.se.com/us/en/product/XB4BD33/',
    attributes: { series: 'Harmony XB4', positions: 3, returnType: 'stay-put', contactType: '2NO', application: 'HOA', mounting: '22mm' },
  },
  {
    type: 'part',
    manufacturer: 'Schneider Electric',
    partNumber: 'XB5AD21',
    description: 'Harmony XB5 Selector Switch - 2-Position, Stay-Put, 1NO',
    category: 'selector-switch',
    voltage: '600VAC',
    current: '10A',
    certifications: ['UL', 'CE', 'CSA'],
    symbolCategory: 'iec-no-contact',
    datasheetUrl: 'https://www.se.com/us/en/product/XB5AD21/',
    attributes: { series: 'Harmony XB5', positions: 2, returnType: 'stay-put', contactType: '1NO', mounting: '22mm' },
  },
  {
    type: 'part',
    manufacturer: 'Schneider Electric',
    partNumber: 'XB5AD33',
    description: 'Harmony XB5 Selector Switch - 3-Position (HOA), Stay-Put, 2NO',
    category: 'selector-switch',
    voltage: '600VAC',
    current: '10A',
    certifications: ['UL', 'CE', 'CSA'],
    symbolCategory: 'iec-no-contact',
    datasheetUrl: 'https://www.se.com/us/en/product/XB5AD33/',
    attributes: { series: 'Harmony XB5', positions: 3, returnType: 'stay-put', contactType: '2NO', application: 'HOA', mounting: '22mm' },
  },
];
